# Generated by Django 3.2.9 on 2021-11-18 07:09

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0002_alter_flexpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='content',
            field=wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True)), ('text', wagtail.core.blocks.RichTextBlock(help_text='Add additional text', required=True)), ('img', wagtail.images.blocks.ImageChooserBlock(required=True))])), ('servisies', wagtail.core.blocks.StreamBlock([('title', wagtail.core.blocks.CharBlock(help_text='Заголовок слева', required=True)), ('number', wagtail.core.blocks.CharBlock(help_text='Номер слева', required=True))]))], blank=True, null=True),
        ),
    ]
