# Generated by Django 3.2.9 on 2021-11-22 06:30

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0007_alter_flexpage_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flexpage',
            options={'verbose_name': 'Кастомная Страница', 'verbose_name_plural': 'Кастомная Страница'},
        ),
        migrations.AlterField(
            model_name='flexpage',
            name='content',
            field=wagtail.core.fields.StreamField([('employer', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True)), ('text', wagtail.core.blocks.RichTextBlock(help_text='Add additional text', required=True)), ('img', wagtail.images.blocks.ImageChooserBlock(required=False))]))], blank=True, null=True),
        ),
    ]
