# Generated by Django 3.2.9 on 2021-11-25 09:40

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0008_auto_20211122_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='content',
            field=wagtail.core.fields.StreamField([('employer', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='Введите ФИО сотрудника', required=True)), ('position', wagtail.core.blocks.CharBlock(help_text='Введите должность сотрудника', required=True)), ('text', wagtail.core.blocks.RichTextBlock(help_text='Введите дополнительный текст', required=False)), ('img', wagtail.images.blocks.ImageChooserBlock(required=False))]))], blank=True, null=True),
        ),
    ]
