# Generated by Django 3.2.9 on 2021-11-26 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='code',
            options={'verbose_name': 'Добавить кастомный код', 'verbose_name_plural': 'Добавить кастомный код'},
        ),
    ]
