# Generated by Django 3.2.9 on 2021-11-26 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_code_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Code',
        ),
    ]
