# Generated by Django 3.2.9 on 2021-11-26 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Code',
        ),
    ]
