# Generated by Django 3.2.9 on 2021-11-28 08:18

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_citypage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footerr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodytext', wagtail.core.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'подвал правый',
                'verbose_name_plural': 'подвал правый',
            },
        ),
    ]
