# Generated by Django 3.2.9 on 2021-12-01 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20211130_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='code',
        ),
    ]
