# Generated by Django 3.2.9 on 2021-12-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_homepage_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='redirect_url',
            field=models.URLField(blank=True, default='', help_text='Ссылка перенаправления'),
        ),
    ]
