# Generated by Django 3.2.9 on 2021-12-03 03:56

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20211202_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citypage',
            name='blog_image',
        ),
        migrations.AlterField(
            model_name='citypage',
            name='content',
            field=wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Добавьте заголовок', required=True)), ('text', wagtail.core.blocks.RichTextBlock(help_text='Добавьте текст', required=True)), ('img', wagtail.images.blocks.ImageChooserBlock(required=False))])), ('full_richtext', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.RichTextBlock(help_text='Добавьте текст', required=True))])), ('picture', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.RichTextBlock(help_text='Добавьте текст', required=False)), ('img', wagtail.images.blocks.ImageChooserBlock(required=True))]))], blank=True, null=True),
        ),
    ]
