# Generated by Django 3.2.9 on 2021-11-25 09:40

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('content', wagtail.core.fields.StreamField([('employer', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='Введите ФИО сотрудника', required=True)), ('position', wagtail.core.blocks.CharBlock(help_text='Введите должность сотрудника', required=True)), ('text', wagtail.core.blocks.RichTextBlock(help_text='Введите дополнительный текст', required=False)), ('img', wagtail.images.blocks.ImageChooserBlock(required=False))]))], blank=True, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Сотрудники',
                'verbose_name_plural': 'Сотрудники',
            },
            bases=('wagtailcore.page',),
        ),
    ]
