# Generated by Django 3.2.9 on 2021-11-24 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burger_menus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='link_url',
        ),
    ]
