# Generated by Django 3.2.9 on 2021-11-24 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('burger_menus', '0002_remove_menuitem_link_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='link_page',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='link_title',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
