# Generated by Django 3.2.9 on 2021-11-27 02:48

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('burger_menus', '0003_auto_20211125_0512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Бургер-меню', 'verbose_name_plural': 'Бургер-меню'},
        ),
        migrations.AddField(
            model_name='menu',
            name='footer',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
