# Generated by Django 3.2.9 on 2021-11-27 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burger_menus', '0004_auto_20211127_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='footer',
        ),
    ]
