# Generated by Django 3.2.9 on 2021-11-27 03:04

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('burger_menus', '0005_remove_menu_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='footer',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
