# Generated by Django 3.2.9 on 2021-11-27 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burger_menus', '0008_remove_menu_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='footer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
