# Generated by Django 3.2.9 on 2021-11-27 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burger_menus', '0011_menu_footer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='footer',
            new_name='footer_text',
        ),
    ]
