# Generated by Django 3.2.9 on 2021-11-27 04:54

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('burger_menus', '0012_rename_footer_menu_footer_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='footer_text',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
