# Generated by Django 3.2.9 on 2021-11-27 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burger_menus', '0013_alter_menu_footer_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='footer_text',
        ),
    ]
