# Generated by Django 3.2.9 on 2021-11-27 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burger_menus', '0017_alter_menufooter_footer_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menufooter',
            name='footer_text',
        ),
    ]
