# Generated by Django 3.2.9 on 2021-11-27 08:14

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('burger_menus', '0018_remove_menufooter_footer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='menufooter',
            name='footer_text',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
