# Generated by Django 3.2.9 on 2021-11-27 08:33

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('burger_menus', '0022_auto_20211127_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menufooter',
            name='footer_phone',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menufooter',
            name='footer_text',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
