# Generated by Django 3.2.9 on 2021-11-26 05:18

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_code', '0004_delete_customstyle'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title')),
            ],
            options={
                'verbose_name': 'Добавить Стиль css',
                'verbose_name_plural': 'Добавить Стили css',
            },
        ),
        migrations.CreateModel(
            name='CodeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('css_code', wagtail.core.fields.RichTextField()),
                ('js_code', wagtail.core.fields.RichTextField()),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_items', to='custom_code.customcode')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
