# Generated by Django 3.2.9 on 2021-11-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0005_codeitem_customcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcode',
            name='javascript',
            field=models.CharField(default='code', max_length=500),
        ),
    ]
