# Generated by Django 3.2.9 on 2021-11-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0006_customcode_javascript'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcode',
            name='file',
            field=models.FileField(default='custom.js', upload_to='../CleanOk/static/js/'),
        ),
    ]
