# Generated by Django 3.2.9 on 2021-11-26 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0011_auto_20211126_1526'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CodeItem',
        ),
    ]
