# Generated by Django 3.2.9 on 2021-11-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0012_delete_codeitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customcode',
            options={'verbose_name': 'Добавить Кастомный код', 'verbose_name_plural': 'Добавить Кастомный код'},
        ),
        migrations.AlterField(
            model_name='customcode',
            name='css_file',
            field=models.FileField(default='customer.css', upload_to='css/'),
        ),
    ]
