# Generated by Django 3.2.9 on 2021-12-01 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0013_auto_20211130_0908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customcode',
            options={'verbose_name': 'Добавить Дополнительный код', 'verbose_name_plural': 'Добавить Дополнительный код'},
        ),
    ]
